import Head from 'next/head'
import {
	Button,
	Flex,
	Heading,
	View,
	withAuthenticator,
} from '@aws-amplify/ui-react'
import { API } from 'aws-amplify'
import { FileUploader } from '@aws-amplify/ui-react'
import { useState } from 'react'
import { createRecipe } from '../../src/graphql/mutations'

const CreateRecipe = ({ user, signOut }) => {
	console.log(user)
	const [recipe, setRecipe] = useState({
		title: 'my first recipe',
		description: 'something great is cooking!',
		ingredients: {
			items: ['chicken', 'bread'],
		},
		steps: [{ item: 'buy it' }, { item: 'cook it' }, { item: 'serve it' }],
		status: 'PRIVATE',
		userRecipesId: user.attributes.sub,
		servings: 4,
	})

	const handleSubmit = async () => {
		console.log('first', recipe)

		const res = await API.graphql({
			query: createRecipe,
			variables: { input: { ...recipe } },
		})

		console.log(res.data.createRecipe)
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<View>
				<Flex justifyContent={'end'}>
					<Button variation="destructive" onClick={signOut}>
						sign out
					</Button>
				</Flex>

				<Flex
					justifyContent={'center'}
					alignItems={'center'}
					direction="column"
				>
					<Heading level={2} textAlign={'center'}>
						Create a recipe
					</Heading>

					<View>
						<FileUploader
							shouldAutoProceed={true}
							acceptedFileTypes={['image/*']}
							accessLevel="protected"
							maxFileCount={1}
							onSuccess={(value) => {
								console.log(value)
								setRecipe({ ...recipe, coverImage: value.key })
							}}
						/>
						<Button onClick={handleSubmit}>Submit Recipe</Button>
					</View>
				</Flex>
			</View>
		</>
	)
}

export default withAuthenticator(CreateRecipe)
