import Head from 'next/head'
import {
	Button,
	Flex,
	Heading,
	useTheme,
	View,
	withAuthenticator,
} from '@aws-amplify/ui-react'
import { API, Auth } from 'aws-amplify'
import { useEffect } from 'react'
import { listRecipes } from '../../src/graphql/queries'
import Link from 'next/link'

const MyRecipes = ({ user, signOut }) => {
	console.log({ user })

	const theme = useTheme()

	useEffect(() => {
		//get the current jwt
		Auth.currentAuthenticatedUser().then((data) =>
			console.log(data.signInUserSession.accessToken.jwtToken)
		)
		API.graphql({ query: listRecipes }).then((data) =>
			console.log(data.data.listRecipes)
		)
	}, [])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<View>
				<Flex justifyContent={'end'}>
					<Button variation="destructive" onClick={signOut}>
						sign out
					</Button>
				</Flex>

				<Flex
					justifyContent={'center'}
					alignItems={'center'}
					direction="column"
				>
					<Heading level={2} textAlign={'center'}>
						Welcome to my recipes
					</Heading>
					<a
						href={`http://billing.stripe.com/p/login/test_aEU7uZh2VgkMf8A4gg?prefilled_email=${user.attributes.email}`}
						target="_blank"
						rel="noopener noreferrer"
					>
						Billing portal
					</a>

					<View>
						<Flex justifyContent={'end'}>
							<Link href={'/recipes/create'}>Create a recipe</Link>
						</Flex>
					</View>
				</Flex>
			</View>
		</>
	)
}

export default withAuthenticator(MyRecipes)
