import Head from 'next/head'

const Home = () => {
	return (
		<>
			<Head>
				<title>Create SaaS App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>Welcome to my landing page of features</main>
			<p>
				This page should list the pricing plan but not actually be where
				customers pay
			</p>
			<p>They can start a free trial free, but first will have to signup</p>
			<p>After going trialing</p>
		</>
	)
}

export default Home
